version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:12888:13888;localhost:22888:23888;localhost:32888:33888
    network_mode: host
    volumes:
      - "${DATA_PATH}zk/vol1/zk1-data:/var/lib/zookeeper/data"
      - "${DATA_PATH}zk/vol2/zk1-txn-logs:/var/lib/zookeeper/log"
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:12888:13888;localhost:22888:23888;localhost:32888:33888
    network_mode: host
    volumes:
      - "${DATA_PATH}zk/vol1/zk2-data:/var/lib/zookeeper/data"
      - "${DATA_PATH}zk/vol2/zk2-txn-logs:/var/lib/zookeeper/log"
  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:12888:13888;localhost:22888:23888;localhost:32888:33888
    network_mode: host
    volumes:
      - "${DATA_PATH}zk/vol1/zk3-data:/var/lib/zookeeper/data"
      - "${DATA_PATH}zk/vol2/zk3-txn-logs:/var/lib/zookeeper/log"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:12181,localhost:22181,localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - "${DATA_PATH}kafka/kafka1-data:/var/lib/kafka/data"
  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:12181,localhost:22181,localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - "${DATA_PATH}kafka/kafka2-data:/var/lib/kafka/data"
  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:12181,localhost:22181,localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - "${DATA_PATH}kafka/kafka3-data:/var/lib/kafka/data"

  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    network_mode: host

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    network_mode: host
    ports:
     - 8181:8181
     - 8081:8081
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
     - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:12181,localhost:22181,localhost:32181
     - SCHEMA_REGISTRY_HOST_NAME=localhost
     - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081

  connect:
    build:
      context: ./kafka-connect-in-cluster
    container_name: kafka-connect
    network_mode: host
    ports:
     - 8083:8083
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
     - CONNECT_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092,localhost:39092
     - CONNECT_REST_PORT=8083
     - CONNECT_GROUP_ID=1
     - CONNECT_CONFIG_STORAGE_TOPIC=my_connect_configs
     - CONNECT_OFFSET_STORAGE_TOPIC=my_connect_offsets
     - CONNECT_STATUS_STORAGE_TOPIC=my_connect_statuses
     - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
     - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
     - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://localhost:8081
     - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://localhost:8081
     - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
     - CONNECT_PLUGIN_PATH=/usr/share/java,/etc/kafka-connect/jars

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es02
    ports:
      - 9300:9200
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es03
    ports:
      - 9400:9200
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

networks:
  elastic:
    driver: bridge