version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-3:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
    extra_hosts:
      - "moby:127.0.0.1"

  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    network_mode: host

  schema-registry:
    image: confluentinc/cp-schema-registry
    network_mode: host
    ports:
     - 8181:8181
     - 8081:8081
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
     - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:32181
     - SCHEMA_REGISTRY_HOST_NAME=localhost
     - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081

  connect:
    build:
      context: ./kafka-connect-in-cluster
    network_mode: host
    ports:
     - 8083:8083
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
     - CONNECT_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092,localhost:39092
     - CONNECT_REST_PORT=8083
     - CONNECT_GROUP_ID=1
     - CONNECT_CONFIG_STORAGE_TOPIC=my_connect_configs
     - CONNECT_OFFSET_STORAGE_TOPIC=my_connect_offsets
     - CONNECT_STATUS_STORAGE_TOPIC=my_connect_statuses
     - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
     - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
     - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://localhost:8081
     - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://localhost:8081
     - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
     - CONNECT_PLUGIN_PATH=/usr/share/java,/etc/kafka-connect/jars

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    network_mode: host
